package com.posbilling.posbillingapplication.utility;

public class MonthData {
    public static String[] monthName = {"January",
            "February",
            "March ",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
    };

    /*public static String[] stateNamesMarathi = {"आंध्र प्रदेश",
            "अरुणाचल प्रदेश",
            "आसाम",
            "बिहार",
            "छत्तीसगड",
            "गोवा",
            "गुजरात",
            "हरियाणा",
            "हिमाचल प्रदेश",
            "झारखंड",
            "कर्नाटक",
            "केरळा",
            "मध्य प्रदेश",
            "महाराष्ट्र",
            "मणिपूर",
            "मेघालय",
            "मिझोरम",
            "नागालँड",
            "ओडिशा",
            "पंजाब",
            "राजस्थान",
            "सिक्किम",
            "तामिळनाडू",
            "तेलंगाना",
            "त्रिपुरा",
            "उत्तर प्रदेश",
            "उत्तराखंड",
            "पश्चिम बंगाल"};*/


    public static String[] stateId = {"1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28"
    };

}
